name: bmi_calculator
description: A new Flutter application.

version: 2.2.0+2

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^8.4.0
  firebase_admob: ^0.5.2
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
